package metrics

const (
	TagService     = "service"
	TagPattern     = "pattern"
	TagStep        = "step"
	TagDirection   = "direction"
	TagType        = "type"
	TagOutcome     = "outcome"
	TagOperation   = "operation"
	TagEntity      = "entity"
	TagFromService = "from_service"
	TagToService   = "to_service"
	TagEventType   = "event_type"
	TagRetryReason = "reason"
	TagMethod      = "method"
	TagTopic       = "topic"

	ServiceChoreography  = "choreography"
	ServiceOrchestration = "orchestration"

	DirectionSent     = "sent"
	DirectionReceived = "received"

	TypeEvent   = "event"
	TypeCommand = "command"
	TypeReply   = "reply"

	OutcomeSuccess = "success"
	OutcomeFailure = "failure"

	OperationInsert = "insert"
	OperationUpdate = "update"

	EntityOrder     = "order"
	EntityPayment   = "payment"
	EntityInventory = "inventory"
	EntityShipment  = "shipment"

	RetryReasonOptimisticLock = "optimistic_lock"
	RetryReasonTransientError = "transient_error"
	RetryReasonKafkaError     = "kafka_error"

	StepPayment   = "payment"
	StepInventory = "inventory"
	StepShipping  = "shipping"

	OrdersCreated                = "saga.orders.created"
	OrdersCompleted              = "saga.orders.completed"
	OrdersFailed                 = "saga.orders.failed"
	OrderProcessingTime          = "saga.order.processing.time"
	StepPaymentDuration          = "saga.step.payment.duration"
	StepInventoryDuration        = "saga.step.inventory.duration"
	StepShippingDuration         = "saga.step.shipping.duration"
	SagaTotalDuration            = "saga.total.duration"
	PaymentsSuccess              = "payments.success"
	PaymentsFailed               = "payments.failed"
	PaymentProcessingTime        = "payment.processing.time"
	InventoryReservationsSuccess = "inventory.reservations.success"
	InventoryReservationsFailed  = "inventory.reservations.failed"
	InventoryReservationTime     = "inventory.reservation.time"
	ShippingSuccess              = "shipping.success"
	ShippingFailed               = "shipping.failed"
	ShippingProcessingTime       = "shipping.processing.time"
	CompensationsTotal           = "saga.compensations.total"
	CompensationsPayment         = "saga.compensations.payment"
	CompensationsInventory       = "saga.compensations.inventory"
	CompensationsShipping        = "saga.compensations.shipping"
	CompensationDuration         = "saga.compensation.duration"
	SagaStepsExecuted            = "saga.steps.executed"
	SagaStepsFailed              = "saga.steps.failed"
	CommandsRetryAttempts        = "saga.commands.retry.attempts"
	CommandsRetrySkipped         = "saga.commands.retry.skipped"
	OutboxPublishAttempts        = "saga.outbox.publish.attempts"
	OutboxPublishSuccess         = "saga.outbox.publish.success"
	OutboxPublishFailure         = "saga.outbox.publish.failure"
	OutboxCleanupDeletions       = "saga.outbox.cleanup.deletions"
	OutboxMaxAttemptsExceeded    = "saga.outbox.max.attempts.exceeded"
	OutboxPendingCount           = "saga.outbox.pending.count"
	OutboxFailedCount            = "saga.outbox.failed.count"
	SagaMessagesTotal            = "saga.messages.total"
	SagaDBWritesTotal            = "saga.db.writes.total"
	SagaMessageLatency           = "saga.message.latency"
	SagaMessagesPerTransaction   = "saga.messages.per.transaction"
	SagaDBWritesPerTransaction   = "saga.db.writes.per.transaction"
	KafkaEventSendFailure        = "saga.kafka.event.send.failure"
	KafkaEventSendSuccess        = "saga.kafka.event.send.success"
	KafkaPublishLatency          = "saga.kafka.publish.latency"
	KafkaConsumerLag             = "saga.kafka.consumer.lag"
	KafkaMessageAge              = "saga.kafka.message.age"
	RetryAttempts                = "saga.retry.attempts"
	RetryExhausted               = "saga.retry.exhausted"
	DeadLetterCount              = "saga.deadletter.count"
	IdempotencyCheckCount        = "saga.idempotency.check.count"
	IdempotencyDuplicateDetected = "saga.idempotency.duplicate.detected"
	IdempotencyTableSize         = "saga.idempotency.table.size"

	FrameworkPrefix                    = "saga.framework"
	FrameworkStarted                   = "saga.framework.started"
	FrameworkCompleted                 = "saga.framework.completed"
	FrameworkCompensationStarted       = "saga.framework.compensation.started"
	FrameworkCompensationCompleted     = "saga.framework.compensation.completed"
	FrameworkTimeout                   = "saga.framework.timeout"
	FrameworkRecovered                 = "saga.framework.recovered"
	FrameworkCommandSent               = "saga.framework.command.sent"
	FrameworkReplyReceived             = "saga.framework.reply.received"
	FrameworkCompensationCommandSent   = "saga.framework.compensation.command.sent"
	FrameworkCompensationReplyReceived = "saga.framework.compensation.reply.received"
	FrameworkOutboxAttempt             = "saga.framework.outbox.attempt"
	FrameworkOutboxSuccess             = "saga.framework.outbox.success"
	FrameworkOutboxFailure             = "saga.framework.outbox.failure"
	FrameworkDuplicateReply            = "saga.framework.duplicate.reply"
	FrameworkDuplicateCommand          = "saga.framework.duplicate.command"
	FrameworkDuration                  = "saga.framework.duration"
	FrameworkStepDuration              = "saga.framework.step.duration"
	FrameworkInMemoryCount             = "saga.framework.inmemory.count"
)
