ALTER TABLE saga_instances
    ADD COLUMN IF NOT EXISTS request_id VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE outbox_messages
    ADD COLUMN IF NOT EXISTS request_id VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(255) NOT NULL DEFAULT '';
