# Axon Server SE Configuration
axoniq.axonserver.name=axon-server
axoniq.axonserver.hostname=axon-server
axoniq.axonserver.devmode.enabled=true

# Auto-create default context
axoniq.axonserver.autoconfigure.enabled=true
axoniq.axonserver.autoconfigure.cluster-name=axon-server
axoniq.axononserver.standalone=true
