apiVersion: 1
datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    uid: mimir
    orgID: 1
    url: http://mimir:9009/prometheus
    isDefault: true
    jsonData:
      prometheusType: Mimir
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    orgID: 1
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: mimir
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags:
          - key: service.name
            value: job
      serviceMap:
        datasourceUid: mimir
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
        tags:
          - key: service.name
            value: service_name

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    uid: pyroscope
    orgID: 1
    url: http://pyroscope:4040
    jsonData:
      minStep: 15s

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    orgID: 1
    url: http://loki:3100
    editable: false
    isDefault: false
    jsonData:
      maxLines: 5000
