apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saga-infra

resources:
  - zookeeper.yaml
  - kafka.yaml
  - order-db.yaml
  - payment-db.yaml
  - inventory-db.yaml
  - shipping-db.yaml
  - zipkin.yaml

commonLabels:
  app.kubernetes.io/part-of: saga-pattern
  app.kubernetes.io/component: infrastructure
