---
apiVersion: v1
kind: Namespace
metadata:
  name: saga-infra
  labels:
    app.kubernetes.io/part-of: saga-pattern
    purpose: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: saga-test
  labels:
    app.kubernetes.io/part-of: saga-pattern
    purpose: application-testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: saga-pattern
    purpose: observability
