/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TrackingTrackingIdRouteImport } from './routes/tracking/$trackingId'
import { Route as ProxySplatRouteImport } from './routes/proxy.$'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as AdminShipmentsRouteImport } from './routes/admin/shipments'
import { Route as AdminPaymentRouteImport } from './routes/admin/payment'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as ApiAdminDelayRouteImport } from './routes/api/admin/delay'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackingTrackingIdRoute = TrackingTrackingIdRouteImport.update({
  id: '/tracking/$trackingId',
  path: '/tracking/$trackingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxySplatRoute = ProxySplatRouteImport.update({
  id: '/proxy/$',
  path: '/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentRoute = AdminPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminDelayRoute = ApiAdminDelayRouteImport.update({
  id: '/api/admin/delay',
  path: '/api/admin/delay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/proxy/$': typeof ProxySplatRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/delay': typeof ApiAdminDelayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/proxy/$': typeof ProxySplatRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/api/admin/delay': typeof ApiAdminDelayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/proxy/$': typeof ProxySplatRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/delay': typeof ApiAdminDelayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/shipments'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/proxy/$'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/checkout/'
    | '/orders/'
    | '/api/admin/delay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/shipments'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/proxy/$'
    | '/tracking/$trackingId'
    | '/admin'
    | '/checkout'
    | '/orders'
    | '/api/admin/delay'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/shipments'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/proxy/$'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/checkout/'
    | '/orders/'
    | '/api/admin/delay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProxySplatRoute: typeof ProxySplatRoute
  TrackingTrackingIdRoute: typeof TrackingTrackingIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiAdminDelayRoute: typeof ApiAdminDelayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracking/$trackingId': {
      id: '/tracking/$trackingId'
      path: '/tracking/$trackingId'
      fullPath: '/tracking/$trackingId'
      preLoaderRoute: typeof TrackingTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/$': {
      id: '/proxy/$'
      path: '/proxy/$'
      fullPath: '/proxy/$'
      preLoaderRoute: typeof ProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment': {
      id: '/admin/payment'
      path: '/payment'
      fullPath: '/admin/payment'
      preLoaderRoute: typeof AdminPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/delay': {
      id: '/api/admin/delay'
      path: '/api/admin/delay'
      fullPath: '/api/admin/delay'
      preLoaderRoute: typeof ApiAdminDelayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentRoute: typeof AdminPaymentRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentRoute: AdminPaymentRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProxySplatRoute: ProxySplatRoute,
  TrackingTrackingIdRoute: TrackingTrackingIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiAdminDelayRoute: ApiAdminDelayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
