global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'choreography-services'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - '192.168.11.152:8081'
          - '192.168.11.152:8082'
          - '192.168.11.152:8083'
          - '192.168.11.152:8084'
        labels:
          pattern: choreography
          service_group: core

  - job_name: 'orchestration-services'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - '192.168.11.152:8085'
          - '192.168.11.152:8086'
          - '192.168.11.152:8087'
          - '192.168.11.152:8088'
        labels:
          pattern: orchestration
          service_group: core

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.11.152:9092']
        labels:
          service: kafka
