x-common: &common
  networks:
    - saga-network
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

x-db-depend: &db-depend
  <<: *common
  depends_on:
    signoz-clickhouse:
      condition: service_healthy

services:
  signoz-init-clickhouse:
    <<: *common
    image: clickhouse/clickhouse-server:25.5.6
    container_name: signoz-init-clickhouse
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    restart: on-failure
    volumes:
      - signoz_clickhouse_user_scripts:/var/lib/clickhouse/user_scripts/

  signoz-zookeeper-1:
    <<: *common
    image: signoz/zookeeper:3.7.1
    container_name: signoz-zookeeper-1
    user: root
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
    volumes:
      - signoz_zookeeper_1:/bitnami/zookeeper
    healthcheck:
      test: ["CMD-SHELL", "curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null"]
      interval: 30s
      timeout: 5s
      retries: 3

  signoz-clickhouse:
    <<: *common
    image: clickhouse/clickhouse-server:25.5.6
    container_name: signoz-clickhouse
    tty: true
    depends_on:
      signoz-init-clickhouse:
        condition: service_completed_successfully
      signoz-zookeeper-1:
        condition: service_healthy
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    volumes:
      - ./signoz/clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml:ro
      - ./signoz/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - signoz_clickhouse_user_scripts:/var/lib/clickhouse/user_scripts/
      - signoz_clickhouse:/var/lib/clickhouse/
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  signoz:
    <<: *db-depend
    image: signoz/signoz:${VERSION:-v0.121.1}
    container_name: signoz
    ports:
      - "8080:8080"
    volumes:
      - signoz_sqlite:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://signoz-clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - SIGNOZ_TOKENIZER_JWT_SECRET=local-dev-secret
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  signoz-otel-collector:
    <<: *db-depend
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.144.3}
    container_name: signoz-otel-collector
    user: root
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate sync check &&
        /signoz-otel-collector --config=/etc/otel-collector-config.yaml
    volumes:
      - ./signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux,deployment.environment=local
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://signoz-clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    ports:
      - "13133:13133"

  signoz-telemetrystore-migrator:
    <<: *db-depend
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.144.3}
    container_name: signoz-telemetrystore-migrator
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://signoz-clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate bootstrap &&
        /signoz-otel-collector migrate sync up &&
        /signoz-otel-collector migrate async up
    restart: on-failure

networks:
  saga-network:
    external: true

volumes:
  signoz_clickhouse:
  signoz_clickhouse_user_scripts:
  signoz_sqlite:
  signoz_zookeeper_1:
